version: 2
models:
  - name: stg_measles_coverage
    description: "Staging view for measles vaccination coverage (MCV1/MCV2) by country and year"
    columns:
      - name: country_code
        description: "ISO3 country code"
        tests:
          - not_null

      - name: country_name
        description: "Country name uppercase"
        tests:
          - not_null

  - name: stg_measles_cases
    description: "Staging view for reported measles cases by country and year."
    columns:
      - name: country_code
        description: "ISO3 country code."
        tests:
          - not_null

      - name: country_name
        description: "Country name in uppercase."
        tests:
          - not_null

      - name: region
        description: "Region (e.g. WHO or UN region)."

      - name: measles_cases
        description: "Number of reported measles cases in that country-year."
